DocumentManagementWeb/Controllers/AdminPannelController.cs
using DocumentManagementWeb.Data;
using DocumentManagementWeb.Models;
using DocumentManagementWeb.Utility;
using DocumentManagementWeb.VM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Data;

namespace DocumentManagementWeb.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class AdminPannelController : Controller
    {
        public IWebHostEnvironment _webHostEnvironment;
        public ApplicationDbContext _db;
        public AdminPannelController(IWebHostEnvironment webHostEnvironment, ApplicationDbContext db)
        {
            _webHostEnvironment = webHostEnvironment;
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(IFormFile file, string email, string notification)
        {
            var emails = _db.Users.ToList();
            var filePath = _webHostEnvironment.ContentRootPath + "\\UserFolders\\";
            filePath += $"{email}\\";

            



            if (emails.Where(u => u.UserName == email).IsNullOrEmpty())
            {
                ModelState.AddModelError("Email Doesn't Exist", "This Email Doesn't Exist , Please Enter A Valid Email.");

            }
            if (!Directory.Exists(filePath))
            {
                Directory.CreateDirectory(filePath);

            }
            if (ModelState.IsValid)
            {
                filePath += $"{file.FileName}";
                if (filePath.Length >= 260)
                {
                    ModelState.AddModelError("name Too Large", "This File Name Is Too Large Please Rename It.");
                    return View();

                }
                using var fileStream = new FileStream(filePath, FileMode.Create);
                await file.CopyToAsync(fileStream);
                Notification notify = new Notification()
                {
                    applicationUser = _db.Users.FirstOrDefault(u => u.Email == email),

                    Msg = notification
                };
                //_db.FileModels.add
                FileModel fileModel = new()
                {
                    FileName = file.FileName,
                    CreatedAt = DateTime.Now,
                    UserName = email
                };
                _db.FileModels.Add(fileModel);
                _db.Notifications.Add(notify);
                _db.SaveChanges();


            }


            return View();
        }
        public IActionResult Pannel()
        {
            string path = _webHostEnvironment.ContentRootPath + "\\UserFolders\\";
            MainVM mainVM = new MainVM();
            mainVM.files = new List<FileModel>();

            if (Directory.Exists(path))
            {
                var emails = _db.Users.ToList();
                string[] dirs = Directory.GetDirectories(path, "*", SearchOption.TopDirectoryOnly);

                foreach (string dir in dirs)
                {

                    string[] filePaths = Directory.GetFiles(dir);
                    foreach (string filePath in filePaths)
                    {
                        FileInfo file = new FileInfo(filePath);


                        mainVM.files.Add(new FileModel { FileName = Path.GetFileName(filePath), CreatedAt = file.CreationTime, UserName = dir.Replace($"{path}", "") });

                    }
                }
                return View(mainVM);

            }
            return View();
        }



        public IActionResult DownloadFile(string filename)
        {
            if (ModelState.IsValid)
            {



                //Build the File Path.
                var file = _db.FileModels.FirstOrDefault(u => u.FileName == filename);
                if (file != null)
                {
                    var email = file.UserName;

                    string path = _webHostEnvironment.ContentRootPath + "\\UserFolders\\" + $"{email}\\";
                    //Read the File data into Byte Array.
                    string[] filePaths = Directory.GetFiles(path);
                    path += filename;

                    if (filePaths.Contains(path))
                    {
                        byte[] bytes = System.IO.File.ReadAllBytes(path);

                        //Send the File to Download.
                        return File(bytes, "application/octet-stream", filename);

                    }
                    else
                    {
                        return RedirectToAction(nameof(Pannel));

                    }
                }
                else
                {
                    return RedirectToAction(nameof(Pannel));
                }

            }
            else
            {
                return RedirectToAction(nameof(Pannel));
            }

        }


        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            string path = _webHostEnvironment.ContentRootPath + "\\UserFolders\\";
            MainVM mainVM = new MainVM();
            mainVM.files = new List<FileModel>();

            if (Directory.Exists(path))
            {

                var emails = _db.Users.ToList();
                string[] dirs = Directory.GetDirectories(path, "*", SearchOption.TopDirectoryOnly);

                foreach (string dir in dirs)
                {

                    string[] filePaths = Directory.GetFiles(dir);
                    foreach (string filePath in filePaths)
                    {
                        FileInfo file = new FileInfo(filePath);


                        mainVM.files.Add(new FileModel { FileName = Path.GetFileName(filePath), CreatedAt = file.CreationTime, UserName = dir.Replace($"{path}", "") });

                    }

                }
                return Json(new
                {
                    data = mainVM.files
                });
            }
            return View();

        }
        #endregion


    }
}

DocumentManagementWeb/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DocumentManagementWeb.Data;
using DocumentManagementWeb.Models;
using DocumentManagementWeb.VM;
using Microsoft.AspNetCore.Hosting;
using DocumentManagementWeb.Utility;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace DocumentManagementWeb.Controllers
{
    public class DevicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DevicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Devices

        public async Task<IActionResult> Index()
        {
            return _context.Devices != null ?
                        View(await _context.Devices.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Devices'  is null.");
        }

        // GET: Devices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }

            var device = await _context.Devices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }

        // GET: Devices/Create
        [Authorize(Roles = SD.Role_Admin)]

        public IActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.Role_Admin)]

        public async Task<IActionResult> Create([Bind("Id,IP,Name,CreatedDateTime,UpdatedDateTime")] Device device)
        {
            if (ModelState.IsValid)
            {
                device.CreatedDateTime= DateTime.Now;
                device.UpdatedDateTime= DateTime.Now;
                _context.Add(device);
                await _context.SaveChangesAsync();
                var emails = _context.Users.ToList();
                foreach(var email in emails)
                {
                    Notification n = new Notification()
                    {
                        applicationUser = email,

                        Msg = $" A New Device Was Added with IP = {device.IP} And Name = {device.Name} At {device.CreatedDateTime}"
                    };
                    _context.Notifications.Add(n);
                    _context.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(device);
        }

        // GET: Devices/Edit/5
        [Authorize(Roles = SD.Role_Admin)]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }

            var device = await _context.Devices.FindAsync(id);
            if (device == null)
            {
                return NotFound();
            }
            return View(device);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.Role_Admin)]

        public async Task<IActionResult> Edit(int id, [Bind("Id,IP,Name,CreatedDateTime,UpdatedDateTime")] Device device)
        {
            if (id != device.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    device.UpdatedDateTime = DateTime.Now;
                    _context.Update(device);
                    await _context.SaveChangesAsync();
                    var emails = _context.Users.ToList();
                    foreach (var email in emails)
                    {
                        Notification n = new Notification()
                        {
                            applicationUser = email,

                            Msg = $" A Device Was Updated Now with IP = {device.IP} And Name = {device.Name} At {device.UpdatedDateTime}"
                        };
                        _context.Notifications.Add(n);
                        _context.SaveChanges();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeviceExists(device.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(device);
        }

        // GET: Devices/Delete/5
        [Authorize(Roles = SD.Role_Admin)]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Devices == null)
            {
                return NotFound();
            }

            var device = await _context.Devices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (device == null)
            {
                return NotFound();
            }

            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = SD.Role_Admin)]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Devices == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Devices'  is null.");
            }
            var device = await _context.Devices.FindAsync(id);
            if (device != null)
            {
                _context.Devices.Remove(device);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeviceExists(int id)
        {
            return (_context.Devices?.Any(e => e.Id == id)).GetValueOrDefault();
        }


        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {

            var tmp = await _context.Devices.ToListAsync();

            return Json(new
            {
                Data = tmp,
            });
        }
        #endregion



    }
}

DocumentManagementWeb/Views/Shared/_Layout.cshtml
@using DocumentManagementWeb.Utility;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DocumentManagementWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DocumentManagementWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DocumentManagementWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="register" asp-controller="AdminPannel" asp-action="Pannel"> Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="register" asp-controller="AdminPannel" asp-action="Index"> New Doc</a>
                            </li>
                            
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="register" asp-controller="Devices" asp-action="Index"> Devices</a>
                        </li>


                    </ul>
                    @*<div>
                        <partial name="_SelectLanguage" />
                    </div>*@
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DocumentManagementWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>